MyScore/Models/Event.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyScore.Models
{
	public class Event
	{
	}
}

MyScore/Models/Match.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyScore.Models
{
	public class Match
	{
		public string Home { get; set; }
		public string Away { get; set; }
		public string Place { get; set; }
		public DateTime dateTime = DateTime.Now;
		public int[] score = new int[2] { 0, 0 };
		public string Referee { get; set; }
		//List<Event> events;
		public long UserId { get; set; }
		public string League { get; set; }
    }
}

MyScore/Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyScore.Models
{
	public class Person
	{
	}
}

MyScore/Models/Team.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyScore.Models
{
	public class Team
	{
	}
}

MyScore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyScore.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

MyScore/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyScore.Models;

namespace MyScore.Controllers
{
    public class MatchController : Controller
    {
        // GET: Match
        public ViewResult Index()
        {
            return View();
        }

		[HttpGet]
		public ViewResult NewMatchForm()
		{
			return View();
		}

		[HttpPost]
		public ViewResult NewMatchForm(Match match)
		{
			return View("ShowMatch",match);
		}
    }
}

MyScore/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        @Html.ActionLink("Nowy mecz", "NewMatchForm", "Match")
    </div>
</body>
</html>

MyScore/Views/Match/Index.cshtml
@model MyScore.Models.Match

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <p>Nowy Mecz</p>
        <p>@Model.place</p>
    </div>
</body>
</html>

MyScore/Views/Match/NewMatchForm.cshtml
@model MyScore.Models.Match

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NewMatchForm</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        <p>Gospodarze: @Html.TextBoxFor(x => x.Home)</p>
        <p>Goście: @Html.TextBoxFor(x => x.Away)</p>
        <p>Miejsce: @Html.TextBoxFor(x => x.Place)</p>
        <p>Sędzia: @Html.TextBoxFor(x => x.Referee)</p>
        <p>Liga: @Html.TextBoxFor(x => x.League)</p>

        <input type="submit" value="Stwórz"/>
    }
</body>
</html>

MyScore/Views/Match/ShowMatch.cshtml
@model MyScore.Models.Match

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowMatch</title>
</head>
<body>
    <div> 
        <p>Gospodarze: @Model.Home</p>
        <p>Goście: @Model.Away</p>
        <p>Miejsce: @Model.Place</p>
        <p>Sędzia: @Model.Referee</p>
        <p>Liga: @Model.League</p>
    </div>
</body>
</html>

MyScore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>